version: "2"
services:

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector-dev:latest
    command: ["--config=/etc/otel-collector-config.yaml",  "--log-level=DEBUG"] 
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    #ports:
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one
