receivers:
  otlp:
    protocols:
      grpc: 
        endpoint: 0.0.0.0:55680
      http: 
        endpoint: 0.0.0.0:55681
       
processors:
  batch:
  queued_retry:

exporters:
  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 200
  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto

  jaeger:
    endpoint: jaeger-all-in-one:14250
    insecure: true



service:
  extensions:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, queued_retry]
      exporters: [logging, zipkin, jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
